title: "Jacob Elsey"
author: "Jacob Elsey"
description: "Johns Hopkins University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "ElseyJG_CV.pdf", title: "CV"}
  - {title: "Lab", url: "https://www.hopkinsmedicine.org/research/labs/veit-stuphorn-laboratory"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jelsey2@jh.edu"}
  - {title: Github, icon: github, url: "https://github.com/elseyjg"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/elseyjg"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
